<a href="https://colab.research.google.com/github/zenvius/Numpy_Notes/blob/main/My_Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#what is Numpy?
#it is a core library for scientific computing in python
#The central object in numpy is   "Numpy array's"
#what is numpy array?
#Array's are high performance multidimensional objects which is designed specifically to perform maths operations

In [ ]:
#How many types of array's?
#three types
#1D array --> array's with 0 cols and with specific rows
#2D array ---> it is like tabular data having rows and cols  with axis 0 and axis 1
#3D array ---> multidimesional array's with axis0,axis1,axis2

In [ ]:
#what are all different use cases and mathematical operations that can be acheived easily with Numpy
""" 1. Dot Product/ inner product
    2. matrix multiplication
    3. element wise matrix product
    4. solving the linear systems
    5. inverse
    6. determinent
    7. choose the random number(gussian/uniform distribution)
    8. statistics """

In [ ]:
#Installation of Numpy
#use PIP --means python pacakage manager
! pip install numpy

In [ ]:
#import the package numpy
import numpy as np

In [ ]:
#how can we check the version of numpy
np.__version__

'1.26.4'

In [ ]:
#What is difference between list and numpy array?
""" array:- Array can take homogenous data
            Array's are faster than the list becuase these are immutable
            Array's are having fixed memory"""

In [ ]:
#array's--> ordered, immutable, also it allows the duplicates

**Central object in Numpy is Numpy Array's**

In [ ]:
a = np.array([1,2,3,4])
print(a)
#How can we create an array?
#array's are created from existing data(list,tuple,dictionary)
#i want to know the shape of the array
a.shape
#i want to know the element data types in array's
a.dtype
#i want to know the dimnsions of the array
a.ndim
#i want to know total number of elements in the array
a.size
# print(len(a))
#i want to know the size in bytes of each element
a.itemsize

**essential methods in NP**

In [ ]:
#access and change the elements in the array
b = np.array([1,2,3])
print(b[1])
print(b[::-1])

In [ ]:
#By using index position number we can replace the items from array
b[0] = 5
print(b)

[5 2 3]


**element wise math operation**

In [ ]:
c = np.array([2,0,3])
print(b + c)
#Note:- when applying arthamatic operation on two array's. The arrays has to be in same length or size
#Task:- apply all the arthmetic operations
#what is vector addition?
#when applying addition operator to the array's of same length is known as vector addition.

In [ ]:
#i want to know the sum of elements in an array?
d = np.array([5,6,7])
print(d)
print(d.sum())
#i want to know the min element in an array
print(d.min())
#i want to know the max element in an array
print(d.max())

**Array's Vs List**

In [ ]:
l = [1,2,3]
#creat an array with above list
d = np.array(l)
#adding new items to the list
l.append(4)
# print(l)
#add the new item to the array
#d.append(5)  #we cannot add the items in an array
#How can we add new items in the array
#if you want add new item to an array create a new array
a1 = d + np.array([6])
print(a1)
#Note:- when you are adding anoter array to existing array it must be in same size or new array can have 1 element

In [ ]:
#find the sqrt of the below array
a2 = np.array([1,2,3,4,5])
print(np.sqrt(a2))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
a3 = np.append(d,a2)
a3
#we can use append to create new array and add the elements of two arrays

array([1, 2, 3, 1, 2, 3, 4, 5])

**21-11-2024**

Dot Products

In [ ]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for i in range(len(a)):
  dot += a[i]*b[i]   #dot = dot + a[i]*b[i]
print(dot)
#vector multiplication of array's and sum of elements fo the result
#multiply each corresponding element and make sum


In [ ]:
#easy with numpy
dot = np.dot(a,b)
print(dot)

In [ ]:
#manual method
c = a*b
d =np.sum(c)
print(d)

In [ ]:
e = a.dot(b)
print(e)

In [ ]:
f = a@b
print(f)

**speed test b/w Array vs List**

In [ ]:
#import a time calculator to see the variation
from timeit import default_timer as timer

#create to random array
a= np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array in the form of list
c = list(a)
d = list(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i] # dot = dot+ c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)

#take the timer
start = timer()
for t in range(T):
  dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end - start

print("time with list",t1)
print("time with array", t2)

print("ratio", t1/t2)

time with list 0.44084905299996535
time with array 0.0029967219998070505
ratio 147.11042700268834


In [ ]:
s1 = {1,2,3,4}
a = np.array(s1)
print(a)
#we cannot create array from the sets beacuse sets are unordered

**Multidimesional array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#how can we access the elements from 2d array
#print the entire row?
#a[row index number]
print(a[0])
#How access the particular value from particular column?
#[row_index,colindex]
print(a[0,1])
#access the 6 from above array

[1 2 3]
2


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
#how can i print entire values of the 1st column
print(b[:,1])

In [ ]:
#how can i print entire 1st column
b[0]
b[0,:]

In [ ]:
b[:1] #first row
b[:2] #print 1st    2_ rows

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[1:] #the values are printing from with given row_index and by default it is printing the entire values
b[2:]

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
#Transpose --> convert rows into columns and columns into rows
print(a)
print(a.T)

In [ ]:
#Matrix multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#apply dot product on above array's
c = np.dot(a,b)
#c = a@b
print(c)

[[13 16]
 [29 36]]


In [ ]:
#find the inverse of array a
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)
a

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1, 2],
       [3, 4]])

In [ ]:
#how can i find the diagonal of array a
e = np.diag(a)
print(e)

[1 4]


In [ ]:
#diagonal on vector returns the matrix
c = np.diag([1,4,5])
print(c)

22-11-2024

Indexing, and slicing, boolean indexing

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#will give the dimensionality of an array
a.ndim
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#how can we print second column all values
print(a[:,1]) #printing 1d then how can we print in 2d
print(a[0:3,3:4])
print(a[:,-1:])

In [ ]:
print(a[:,3])

In [ ]:
#print only 11
print(a[2,2])

**Boolean**

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

In [ ]:
#print the number which is more than 2
print(a[a>2])

In [ ]:
bool_index = a>2
print(bool_index)

In [ ]:
l = [1,2,3,4]
print(l*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
b = np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [ ]:
#np.where(condition,true,flase)
a = np.array([[1,2],[3,4],[5,6]])
# print(a)
c = np.where(a>2,a,-1)
print(c)

In [ ]:
#compute the indexes where the condition is true
#argwhere()
a = np.array([10,19,20,30,41,50,61])
even = np.argwhere(a%2==0).flatten()
print(even)
#if you want to see the values
a_even = a[even]
print(a_even)

[0 2 3 5]
[10 20 30 50]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
even = np.argwhere(a%2==0)
print(even)
a_even = a[even]
print(a_even)

**Reshaping of Arrays**

In [ ]:
#create a range of arrays
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#print an range number in array from 1,10
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#reshae the above array into 3 rows and 3 columns
b = a.reshape(5,2)  #reshape(row,col)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


25-11-2024

In [ ]:
#generate a rangfe of array upto 6
import numpy as np
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [ ]:
#convert the above array into 2rows and 3 columns
b=a.reshape(2,3)
print(b)

In [ ]:
#Newaxis:- it is used to create a newaxis in the data
print(a.shape)

In [ ]:
#newaxis
d = a[np.newaxis,:]
d
d.shape
d.T

In [ ]:
e = a[:,np.newaxis]
print(e)
e.shape

In [ ]:
f = a.T
print(f.shape)

In [ ]:
#why we are using np.newaxis?
#needed when model requires the data to be shaped in a certain manner
#Note:- Transpose can be applicable on 2d arrays

#Concatenation

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#combine or concatenate the above 2 arrays in to 1d array
c = np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


In [ ]:
#add new rows
d = np.concatenate((a,b),axis=0)
print(d)

In [ ]:
print(b)
print(b.T)

In [ ]:
#add new column:- Note that we have to transpose the array 'b'

e = np.concatenate((a,b.T),axis=1)
e

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
h = np.concatenate((a,b),axis=1)
h
#how can i print the values of the 1st row h
print(h[0,:])
print(h[0])

**Hstack**

In [ ]:
#hstack:- stack array in sequence horizentally(column wise)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#c = np.concatenate((a,b),axis=None)
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
d = np.hstack((a,b))
d

**Vstack**

In [ ]:
#vstack:- stack array's in sequence vertically(row wise)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c= np.vstack((a,b))
print(c)
#Note:- when applying vstack on 1d array it converts the array in to 2d by default

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
d = np.vstack((a,b))
d

**Broadcasting**

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,1])
z = x+y
print(x+y)
"""Broadcasting isa powerfull mechanism that allows numpy to work with different
arrays of different shapes when performing the arthametic operations"""

**copying**

In [ ]:
a = np.array([1,2,3])
b = a  #only copies the references
b[0] = 42
print(a)

[42  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()  #actual copy
b[0]= 6
print(a)
print(b)
#using copy() if you make any changes in the new array the old array doesn't changes

**Data Types**

In [ ]:
#how can we find thye data type of an array
a = np.array([1,2,3],dtype=np.int32)
a.dtype

dtype('int32')

In [ ]:
b = np.array([1.0,2.0],dtype=np.float32)
b.dtype

dtype('float32')

**Generating Arrays**

In [ ]:
#genrate an array of zeros which is having 2 rows and 3 cols
a = np.zeros((2,3)) #size it as a tuple
print(a)

In [ ]:
#genrate an array of ones which is having 2 rows and 3 cols
b = np.ones((2,3))
print(b)


In [ ]:
#generate an array of specific value with specific rows and cols
c = np.full((3,3),5.0)
print(c)

In [ ]:
#genarate an identity matrix
d = np.eye(3)
print(d)

In [ ]:
#arange of up to 9
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#linspace:- splits the data into specific parts equally
h = np.linspace(0,10,6)
#linspace(start,end,no. of partititons)
print(h)

[ 0.  2.  4.  6.  8. 10.]


26-11-2024

**Random Numbers**

In [ ]:
import numpy as np

In [ ]:
#generate random numbers uniformily distributed from 0-1
a = np.random.random((3,2))
print(a)

[[0.95304056 0.07460665]
 [0.35581082 0.47282   ]
 [0.61384537 0.13958679]]


In [ ]:
#generate an array which is normally distributed or gussian distribution where mean is zero and varience is 1
s = np.random.randn(3,2)
print(s)
#Note:no tuple as a shape, each dimension is a argument

In [ ]:
#generate random.randn numbers upto 10000 and find mean varaience and std
h = np.random.randn(10000)
print(h.mean(),h.var(),h.std())

-0.007477460464284738 0.990865482664875 0.9954222634966906


In [ ]:
#generate an random integers
a = np.random.randint(3,10,size=(3,3))
print(a)

In [ ]:
#generate an random integers from 10 to 20 in the size of 4*4
h = np.random.randint(10, size = (10))
print(h)

In [ ]:
#genrate a number up to 6 and divided in to size of 10
u = np.random.choice(7,size=10)
print(u)

In [ ]:
l = np.random.choice([1,2,3,4],size=10)
print(l)

**Linear Algebra**

In [ ]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#how can we verify this eigenvalues and eigen vectors
#verify -->     e-vec*e-val = a * e-vec
d = eigenvectors[:,0] * eigenvalues[0]
e = a @ eigenvectors[:,0]
print(d,e)

[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]


In [ ]:
print(np.allclose(d,e)) #command to compare the matrix

True


**solving linear systems**

In [ ]:
# x1 +x2 = 2200
# 1.5 x1 + 4x2 = 5050
a = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
# AX = B  <=> x = A**-1 B
X = np.linalg.inv(a).dot(b)
print(X)


[1500.  700.]


In [ ]:
#instead use below method
x = np.linalg.solve(a,b)
print(x)

[1500.  700.]


**Loading a CSV by using Numpy**

In [ ]:
#1.load with ""np.loadtxt()""
data = np.loadtxt('/content/sample_data/california_housing_train.csv',delimiter=",",dtype=np.float32)

In [ ]:
#2. load with "np.genfromtxt()"

In [ ]:
#random Numbers
#Linear algebra
#solving the linear systems
#load a csv file numpy

In [ ]:
#How to check the Numpy array or explore an array?
""" np.shape
    np.ndim
    np.size--> no. of elements in the array
    np.dtype--> finds the data types of each element in array
    np.itemsize"""
#what is 1d,2d,3d array's?
#what is the difference between list and array?
#slicing operations with 1d array?
#how to generate 2d array and slicing operation with 2d array
#reshaping of an array
#how to genrate a range of array
#copying and its advantage
#genrative array
#boolean indexing
#random array's